---
- name: Add *.dev resolver
  become: true
  lineinfile:
    state: present
    line: nameserver 127.0.0.1
    create: true
    dest: /etc/resolver/dev
    mode: 0644

- name: Resolve *.dev to localhost
  lineinfile:
    state: present
    line: address=/dev/127.0.0.1
    create: true
    dest: /usr/local/etc/dnsmasq.conf
    mode: 0644

- name: Copy dnsmasq plist
  become: true
  template:
    src: homebrew.mxcl.dnsmasq.plist.j2
    dest: /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    mode: 0644

- name: Enable autostart dnsmasq
  become: true
  command: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  changed_when: false

- name: Stop dnsmasq
  become: true
  command: launchctl stop homebrew.mxcl.dnsmasq
  changed_when: false

- name: Start dnsmasq
  become: true
  command: launchctl start homebrew.mxcl.dnsmasq
  changed_when: false
