---
- name: Run bcl setup install
  shell: |
    set -o pipefail
    curl -L -s {{ bcl_url }} | bash
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Enable autocomplete for zsh
  blockinfile:
    path: ~/.zshrc
    block: |
      autoload -U +X compinit && compinit
      autoload -U +X bashcompinit && bashcompinit
      source ~/.bash_completion
      export PATH="$HOME/.local/bin:$PATH"

- name: Source zshrc
  become: false
  command: /bin/zsh -c "source ~/.zshrc"
  changed_when: false

- name: Run package installation
  command: |
    bash -lc "cd {{ project_path }} \
    && $HOME/.local/bin/bcl package install"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  when: bcl_package_install
  changed_when: false
