---
- name: Download minio certificate
  get_url:
    url: https://curl.haxx.se/ca/cacert.pem
    dest: /usr/local/etc/nginx/ssl/cacert.pem

- name: Add tenantcloud-root certificate to cacert.pem
  shell: cat /usr/local/etc/nginx/ssl/tenantcloud-rootCA.crt >> /usr/local/etc/nginx/ssl/cacert.pem   # yamllint disable-line rule:line-length
  changed_when: false

- name: Change openssl.cafile string
  lineinfile:
    path: /usr/local/etc/php/{{ php_release }}/php.ini
    regexp: '^openssl.cafile ='
    line: 'openssl.cafile = /usr/local/etc/nginx/ssl/cacert.pem'
    mode: 0644

- name: Change openssl.capath string
  lineinfile:
    path: /usr/local/etc/php/{{ php_release }}/php.ini
    regexp: '^openssl.capath ='
    line: ';openssl.capath ='
    mode: 0644

- name: Linked php
  command: /usr/local/bin/brew link --overwrite --force {{ php_version }}
  changed_when: false

- name: Export PATH
  command: echo 'export PATH="/usr/local/opt/{{ php_version }}/bin:$PATH"' >> ~/.zshrc    # yamllint disable-line rule:line-length
  changed_when: false

- name: Export PATH
  command: echo 'export PATH="/usr/local/opt/{{ php_version }}/sbin:$PATH"' >> ~/.zshrc   # yamllint disable-line rule:line-length
  changed_when: false

- name: Create conf.d directory
  file:
    path: /usr/local/etc/php/{{ php_release }}/conf.d
    state: directory
    mode: 0755

- name: Copy ext-xdebug.ini
  template:
    src: ext-xdebug.ini.j2
    dest: /usr/local/etc/php/{{ php_release }}/conf.d/ext-xdebug.ini
    mode: 0644

- name: Reinstall pkg-config
  command: brew reinstall pkg-config
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Get imagick module exist status
  stat:
    path: /usr/local/lib/php/pecl/{{ php_api_version }}/imagick.so
  register: imagick

- name: Install imagick
  command: pecl install imagick
  args:
    executable: /usr/local/opt/{{ php_version }}/bin/pecl
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
  when: not imagick.stat.exists

- name: Get imagick module exist xdebug
  stat:
    path: /usr/local/lib/php/pecl/{{ php_api_version }}/xdebug.so
  register: xdebug

- name: Install xdebug
  command: pecl install xdebug
  args:
    executable: /usr/local/opt/{{ php_version }}/bin/pecl
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
  when: not imagick.stat.exists

- name: Start service php
  command: brew services start {{ php_version }}
  args:
    executable: /bin/zsh
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Install composer
  shell: |
    set -o pipefail
    curl -sS "{{ composer_url }}" |
    php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
    warn: false
  changed_when: false
