---
- name: Create nginx servers directory
  file:
    path: /usr/local/etc/nginx/servers
    state: directory
    mode: 0777

- name: Create nginx ssl directory
  file:
    path: /usr/local/etc/nginx/ssl
    state: directory
    mode: 0777

- name: Copy nginx configured files
  template:
    src: www.conf.j2
    dest: /usr/local/etc/nginx/servers/home.{{ work_domain }}.conf
    mode: 0644

- name: Copy nginx ssl certificates
  copy:
    src: $HOME/{{ work_dir }}/home.{{ work_domain }}/docs/installation/ssl
    dest: /usr/local/etc/nginx
    mode: 0777
    remote_src: true

- name: Add root certificate to trust
  command: "{{ add_trusted_cert_command }}"
  become: true
  changed_when: false

- name: Copy root private key certificate to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/tenantcloud.dev.key
    dest: $HOME/.minio/private.key
    mode: 0644
    remote_src: true

- name: Copy root public key certificate to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/tenantcloud.dev.crt
    dest: $HOME/.minio/public.crt
    mode: 0644
    remote_src: true

- name: Copy nginx ssl certificates to minio folder
  copy:
    src: /usr/local/etc/nginx/ssl/
    dest: $HOME/.minio
    mode: 0700
    remote_src: true

- name: Add hostname to hosts file
  become: true
  lineinfile:
    state: present
    line: 127.0.0.1 home.{{ work_domain }} {{ work_domain }} www.{{ work_domain }}    # yamllint disable-line rule:line-length
    create: true
    dest: /etc/hosts
    mode: 0644
