---
- name: Copy docker enviromment file
  copy:
    src: $HOME/{{ work_dir }}/{{ docker_dir }}/.env.example
    dest: $HOME/{{ work_dir }}/{{ docker_dir }}/.env
    mode: 0644
    remote_src: true

- name: Change TC_DASHBOARD_DIR
  lineinfile:
    path: $HOME/{{ work_dir }}/{{ docker_dir }}/.env
    regexp: '^TC_DASHBOARD_DIR='
    line: 'TC_DASHBOARD_DIR=~/{{ work_dir }}/home.{{ work_domain }}'
    mode: 0644

- name: Change docker settings
  lineinfile:
    path: $HOME/.docker/config.json
    regexp: '  "credsStore'
    state: absent

- name: Remove docker-credential-osxkeychain
  file:
    path: /usr/local/bin/docker-credential-osxkeychain
    state: absent

- name: Docker login (must "--no-include-email")
  shell: "$(aws ecr get-login --region {{ aws_default_region }} --no-include-email)"    # yamllint disable-line rule:line-length
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Start services via docker-compose
  docker_compose:
    project_src: $HOME/{{ work_dir }}/{{ docker_dir }}
