---
- name: Copy nfs script file
  copy:
    src: "files/nfs.sh"
    dest: "{{ project_path }}/docker/macos/nfs-from-ansible.sh"
    mode: 0777

- name: Run NFS configuration
  become: true
  become_user: "{{ ansible_user }}"
  expect:
    command: |
      bash -lc "cd {{ project_path }} \
      && docker/macos/nfs-from-ansible.sh"
    responses:
      "Password:": "{{ ansible_pass }}"
    timeout: 90
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false

- name: Remove nfs script file
  ansible.builtin.file:
    path: "{{ project_path }}/docker/macos/nfs-from-ansible.sh"
    state: absent

- name: Start services via docker-compose
  command: |
    bash -lc "cd {{ project_path }} \
    && docker-compose up -d"
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  changed_when: false
